# Generated by Django 4.1.1 on 2022-09-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='inspirations',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='user',
        ),
        migrations.AddField(
            model_name='inspiration',
            name='galleries',
            field=models.ManyToManyField(to='main_app.gallery'),
        ),
    ]
